Add milkomeda algorand mainnet
safe-global/safe-deployments pull request #132
Opened 2022-10-22 15:15 UTC by pkakelas

> Network Name: Milkomeda Algorand Mainnet
> New RPC URL: https://rpc-mainnet-algorand-rollup.a1.milkomeda.com
> Chain ID: 2002
> Currency Symbol: mALGO
> Block Explorer URL: https://explorer-mainnet-algorand-rollup.a1.milkomeda.com/

Thanks folks :)

2022-10-24 13:11 UTC, moisses89 commented
Hi @pkakelas could you fill the following form to create the issue and link it with the PR? 
https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+

2022-10-25 00:02 UTC, pkakelas commented
Done!

2022-10-25 13:42 UTC, moisses89 requested changes

2022-10-25 13:42 UTC, moisses89 commented on src/assets/v1.3.0/proxy_factory.json
> +    "2002": "0xE89ce3bcD35bA068A9F9d906896D3d03Ad5C30EC",
Could you review the addressess? some of them are not the deterministic addresses, this is one case. 
```
reusing "SimulateTxAccessor" at 0x59AD6735bCd8152B84860Cb256dD9e96b85F69Da
deploying "GnosisSafeProxyFactory"
```

2022-11-01 14:24 UTC, pkakelas commented
Arghh sorry my bad! @moisses89 fixed it :)

2022-11-04 09:47 UTC, Uxio0 approved these changes
I checked and looks good now, but we cannot merge after @moisses89 approves

2022-11-07 15:18 UTC, moisses89 approved these changes
Looks good to me!

2022-11-07 15:18 UTC, merged