please add ETMP network
safe-global/safe-deployments pull request #173
Opened 2022-12-14 07:34 UTC by LuxesOwen

chainID is already added in chainlist :
eip155-48.json: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-48.json
eip155-49.json: https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-49.json

2022-12-20 12:25 UTC, moisses89 requested changes
I couldn't find a valid RPC https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-48.json for `Ennothem Mainnet Proterozoic` Then I can't validate the addresses.
For testnet also doesn't seems the deterministic addresses, ensure that you are in the correct branch https://github.com/safe-global/safe-contracts#deploy

2022-12-21 09:11 UTC, LuxesOwen commented
we add rpc address in mainnet , and updated ETMP testnet contract address, please check again

2022-12-29 10:50 UTC, moisses89 requested changes

2022-12-29 10:50 UTC, moisses89 commented on src/assets/v1.3.0/compatibility_fallback_handler.json
> +    "49": "0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4",
Did you deploy the contracts on testnet?
```curl --location --request POST 'https://rpc.pioneer.etm.network' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4",
        "latest"
    ],
    "id": 1}'
```
If I ask for the code to the RPC returns empty
```
{"jsonrpc":"2.0","id":1,"result":"0x"}% 
```

2022-12-29 10:50 UTC, moisses89 commented on src/assets/v1.3.0/compatibility_fallback_handler.json
> +    "48": "0x0D2068Bbe4e3975adc8D6701234fBdA115CdAc19",
The contracts should be deployed also in mainnet using the deterministic addresses.

2023-03-14 15:29 UTC, Uxio0 commented
I'm closing this issue due to inactivity

2023-03-14 15:29 UTC, closed without merging