Updated info to add PGN mainnet and testnet
safe-global/safe-deployments pull request #315
Opened 2023-11-02 17:15 UTC by sodew

2023-11-02 21:45 UTC, mmv08 requested changes

2023-11-02 21:45 UTC, mmv08 commented on .history/src/assets/v1.3.0/compatibility_fallback_handler_20231102170232.json
> +{
What are those files? Please remove them

2023-11-02 21:45 UTC, mmv08 commented on src/assets/v1.3.0/compatibility_fallback_handler.json
> +    "58008": "0x1AC114C2099aFAf5261731655Dc6c306bFcd4Dbd",
this address doesn't match the expect address

2023-11-02 21:45 UTC, mmv08 commented on src/assets/v1.3.0/sign_message_lib.json
> +    "424": "0x7cbB62EaA69F79e6873cD1ecB2392971036cFAa4",
This address doesn't match the expected one

2023-11-06 09:19 UTC, sodew commented on .history/src/assets/v1.3.0/compatibility_fallback_handler_20231102170232.json
> +{
These were removed

2023-11-06 10:06 UTC, sodew commented
@mmv08 

Fixed PR so that .history files are removed, and mainnet contracts match expected addresses.

Additionally, removed testnet for now since some of the contracts aren't verified on PGNs end.

2023-11-06 10:20 UTC, mmv08 commented
> Additionally, removed testnet for now since some of the contracts aren't verified on PGNs end.

It is still present in one of the files. Also, it's okay with us if the contract isn't verified since the deployment is deterministic and depends on the hash of the bytecode. If one were to alter the code, it would result in a different address.
https://github.com/safe-global/safe-deployments/pull/315/files#diff-905275e3e6a99d588ff498e27b13efa9ee12d1ae314645f224cecca748ed98feR126

2023-11-06 12:46 UTC, sodew commented
@mmv08 Just added back testnet with expected contract addresses. 

Is there more we need to ensure is done on the PGN side to ensure this PR gets merged?

2023-11-06 13:33 UTC, mmv08 approved these changes

2023-11-06 13:42 UTC, merged