Add Zircuit Mainnet addresses
safe-global/safe-deployments pull request #760
Opened 2024-09-02 14:12 UTC by leonimella

## Add existing chain

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 48900

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL:  https://zircuit1-mainnet.p2pify.com

<br class="Apple-interchange-newline">

Relevant information:
Add any other relevant information like blockexplorer, any annotation...
- Block explorer: https://explorer.zircuit.com/

2024-09-06 08:57 UTC, nlordell commented
We do not support removing existing deployments - you can add it by changing the value to `["canonical", "eip155"]`.

2024-09-06 08:58 UTC, nlordell requested changes
We do not support removing existing deployments - you can add it by changing the value to `["canonical", "eip155"]`.

2024-09-10 13:29 UTC, leonimella commented
> We do not support removing existing deployments - you can add it by changing the value to `["canonical", "eip155"]`.

Thank you for the clarification, @nlordell. I updated the PR.

2024-09-10 13:40 UTC, remedcu approved these changes

2024-09-11 06:22 UTC, nlordell approved these changes

2024-09-11 06:23 UTC, merged