[FEAT] add 1.4.1 contracts deployed on Apechain
safe-global/safe-deployments pull request #892
Opened 2024-12-02 23:28 UTC by jierlich

## Add new chain

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 33139

Relevant information:
RPC: https://rpc.apechain.com

2024-12-03 11:30 UTC, nlordell requested changes
There are deployments missing for 1.4.1 contracts, namely:
- `SafeToL2Migration`
- `SafeMigration`

2024-12-03 18:17 UTC, jierlich commented
> There are deployments missing for 1.4.1 contracts, namely:
> 
> * `SafeToL2Migration`
> * `SafeMigration`

I have deployed and added these contracts

2024-12-04 10:04 UTC, remedcu approved these changes

2024-12-04 18:14 UTC, nlordell approved these changes

2024-12-04 18:14 UTC, merged