feat: add 1.3.0 canonical contracts for HashKey Chain Testnet
safe-global/safe-deployments pull request #893
Opened 2024-12-03 03:53 UTC by HashKeyCloud

HashKey Chain Testnet

Provide the Chain ID (Only 1 chain id per PR).
Chain_ID: 133

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
RPC_URL: https://hashkeychain-testnet.alt.technology

Relevant information:
Block explorer: https://hashkeychain-testnet-explorer.alt.technology

2024-12-03 11:28 UTC, nlordell requested changes
Can you please split this PR into one PR for the 1.3.0 contracts, and another for the 1.4.1 contracts?

2024-12-04 05:13 UTC, HashKeyCloud commented
> Can you please split this PR into one PR for the 1.3.0 contracts, and another for the 1.4.1 contracts?

done.

2024-12-04 09:29 UTC, remedcu approved these changes

2024-12-04 18:16 UTC, nlordell approved these changes

2024-12-04 18:16 UTC, merged